### ISSUE TITLE
Using scalar in typdef and resolvers errors on component creation.

### ISSUE THREAD

**Issue by holmok** [tlivings/graphql-component#21]
In a component that is using the custom scalar (Like `graphql-iso-date`) in the following way:

```javascript
const GraphQLComponent = require('graphql-component')
const { GraphQLDate } = require('graphql-iso-date')

class SomeComponent extends GraphQLComponent {
  constructor () {
    const types = `
    scalar Date
  `
    const resolvers = {
      Date: GraphQLDate,
    }
    super({ types, resolvers })
  }
}

module.exports = SomeComponent
```
...the following error occurs:
```
graphql-component:schema creating component +0ms
  graphql-component:resolver memoized DateTime.name +0ms
/Users/cholmok/work/holmok.com/node_modules/graphql-component/lib/resolvers.js:68
      wrapped[name][resolverName] = memoize(name, resolverName, func.bind(bind));
                                                                     ^

TypeError: func.bind is not a function
    at wrapResolvers (/Users/cholmok/work/holmok.com/node_modules/graphql-component/lib/resolvers.js:68:70)
    at new GraphQLComponent (/Users/cholmok/work/holmok.com/node_modules/graphql-component/lib/index.js:32:23)
    at new BlogComponent (/Users/cholmok/work/holmok.com/server/components/blog-component.js:68:5)
    at Object.<anonymous> (/Users/cholmok/work/holmok.com/server/components/index.js:20:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

It appears this breaks the memoize which is assuming all the values in the resolvers object are functions and breaks when it is not.

**Comment by holmok** [comment]
Hey @tlivings I fixed this.

**Comment by tlivings** [comment]
Thanks for PR!
